"""create risk scores table

Revision ID: 282257eda208
Revises: e1fa5250d0fb
Create Date: 2026-09-04 10:00:00.776155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282257eda208'
down_revision: Union[str, Sequence[str], None] = 'e1fa5250d0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_risk_level'), 'risk_scores', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_scores_transaction_id'), 'risk_scores', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_risk_scores_transaction_reference'), 'risk_scores', ['transaction_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_transaction_reference'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_transaction_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_risk_level'), table_name='risk_scores')
    op.drop_table('risk_scores')
    # ### end Alembic commands ###
