"""create transaction ledger table

Revision ID: e1fa5250d0fb
Revises: e705fc89dcec
Create Date: 2026-09-03 11:57:41.694163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fa5250d0fb'
down_revision: Union[str, Sequence[str], None] = 'e705fc89dcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('payment_intent_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_ledger_payment_intent_id'), 'transaction_ledger', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_transaction_ledger_transaction_id'), 'transaction_ledger', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_transaction_ledger_transaction_reference'), 'transaction_ledger', ['transaction_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_ledger_transaction_reference'), table_name='transaction_ledger')
    op.drop_index(op.f('ix_transaction_ledger_transaction_id'), table_name='transaction_ledger')
    op.drop_index(op.f('ix_transaction_ledger_payment_intent_id'), table_name='transaction_ledger')
    op.drop_table('transaction_ledger')
    # ### end Alembic commands ###
