"""create payment intent and transaction tables

Revision ID: e5e230883454
Revises: 
Create Date: 2026-09-01 18:06:27.774618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e230883454'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_reference', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_intents_idempotency_key'), 'payment_intents', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_intents_merchant_reference'), 'payment_intents', ['merchant_reference'], unique=False)
    op.create_index(op.f('ix_payment_intents_status'), 'payment_intents', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_intent_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_payment_intent_id'), 'transactions', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_transactions_provider_transaction_id'), 'transactions', ['provider_transaction_id'], unique=True)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_reference'), 'transactions', ['transaction_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_provider_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_intent_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payment_intents_status'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_merchant_reference'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_idempotency_key'), table_name='payment_intents')
    op.drop_table('payment_intents')
    # ### end Alembic commands ###
