"""create reconciliation records

Revision ID: e705fc89dcec
Revises: e5e230883454
Create Date: 2026-09-02 16:40:02.492257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e705fc89dcec'
down_revision: Union[str, Sequence[str], None] = 'e5e230883454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processor_status', sa.String(length=30), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_records_provider_transaction_id'), 'reconciliation_records', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_status'), 'reconciliation_records', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_transaction_id'), 'reconciliation_records', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_records_transaction_id'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_status'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_provider_transaction_id'), table_name='reconciliation_records')
    op.drop_table('reconciliation_records')
    # ### end Alembic commands ###
